pipeline {
    agent any

    tools {
        nodejs "react"
    }

    stages {
        stage('checking version') {
            steps {
               bat 'npm -v'
               bat 'node -v'
            }
        }
        stage('Building') {
            steps {   
             bat '''
             cd vite-project
             npm run build
            
             '''
            }
        }
          stage('Archive Artifacts') {
            steps {
                bat '''
                 cd vite-project
                tar -cvf build.tar dist/'''
                archiveArtifacts artifacts: 'vite-project/dist/**', allowEmptyArchive: true
            }
        }
    }
}