pipeline {
    agent any

    tools {
        nodejs "react"
    }

    stages {
        stage('checking version') {
            steps {
               bat 'npm -v'
               bat 'node -v'
            }
        }
        stage('Building') {
            steps {   
             bat '''
             cd vite-project
             npm run build
            
             '''
            }
        }
        stage("static code analisys")
        {
          steps {
                script {
                    def scannerHome = tool name: 'sonarqubescanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                    withSonarQubeEnv('sonarqube') {
                        bat ''' 
                        C:\\ProgramData\\Jenkins\\.jenkins\\tools\\hudson.plugins.sonar.SonarRunnerInstallation\\sonarqubescanner\\bin\\sonar-scanner\
                -Dsonar.projectKey=sivasai-jenkins_react\
                 -Dsonar.sources=VITE-PROJECT\\src\
                 -Dsonar.organization=sivasai-jenkins\
                 -Dsonar.login=3cade956570c411a53b32955b9337e4281d5d6fd\
                 '''
                    }
                }
            }


        }
          stage('Archive Artifacts') {
            steps {
                bat 'powershell.exe -Command "Compress-Archive -Path vite-project\\dist\\* -DestinationPath build.zip"'
 
                // bat 'dir'
                bat 'type build.tar'
                archiveArtifacts artifacts: 'build.zip', allowEmptyArchive: true
            }
        }
    }
}